In [1]:
import nfl_data_py as nfl

In [2]:
import datetime

datetime.datetime.now().year

df = nfl.import_weekly_data(years=list(range(1999, datetime.datetime.now().year - 1)))
df

Downcasting floats.

,player_id,player_name,player_display_name,position,position_group,headshot_url,recent_team,season,week,season_type,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0000003,None,Abdul-Karim al-Jabbar,RB,RB,None,MIA,1999,1,REG,...,0.0,0.292378,0,0.000,0.052632,NaN,NaN,0.0,12.7,13.7
1,00-0000003,None,Abdul-Karim al-Jabbar,RB,RB,None,MIA,1999,2,REG,...,1.0,0.377009,0,0.000,0.117647,NaN,NaN,0.0,5.1,8.1
2,00-0000003,None,Abdul-Karim al-Jabbar,RB,RB,None,MIA,1999,4,REG,...,0.0,-0.699578,0,NaN,0.023810,NaN,NaN,0.0,0.2,0.2
3,00-0000003,None,Abdul-Karim al-Jabbar,RB,RB,None,CLE,1999,7,REG,...,0.0,-0.228454,0,0.000,0.050000,NaN,NaN,0.0,3.5,5.5
4,00-0000003,None,Abdul-Karim al-Jabbar,RB,RB,None,CLE,1999,8,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,3.9,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5592,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,10,REG,...,2.0,1.987017,0,-3.125,0.083333,-0.072072,0.074550,0.0,8.7,10.7
5593,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,12,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,1.8,1.8
5594,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,13,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,2.0,2.0
5595,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,14,REG,...,0.0,-0.144496,0,-0.800,0.026316,-0.031847,0.017181,0.0,1.9,2.9
5596,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,15,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,2.2,2.2

In [3]:
df.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [4]:
df.iloc[0]

player_id                                 00-0000003
player_name                                     None
player_display_name            Abdul-Karim al-Jabbar
position                                          RB
position_group                                    RB
headshot_url                                    None
recent_team                                      MIA
season                                          1999
week                                               1
season_type                                      REG
opponent_team                                    DEN
completions                                        0
attempts                                           0
passing_yards                                    0.0
passing_tds                                        0
interceptions                                    0.0
sacks                                            0.0
sack_yards                                       0.0
sack_fumbles                                       0
sack_fumbles_lost                                  0
passing_air_yards                                0.0
passing_yards_after_catch                        0.0
passing_first_downs                              0.0
passing_epa                                      NaN
passing_2pt_conversions                            0
pacr                                             NaN
dakota                                           NaN
carries                                           16
rushing_yards                                   60.0
rushing_tds                                        1
rushing_fumbles                                  0.0
rushing_fumbles_lost                             0.0
rushing_first_downs                              4.0
rushing_epa                                 6.248771
rushing_2pt_conversions                            0
receptions                                         1
targets                                            1
receiving_yards                                  7.0
receiving_tds                                      0
receiving_fumbles                                0.0
receiving_fumbles_lost                           0.0
receiving_air_yards                              0.0
receiving_yards_after_catch                      0.0
receiving_first_downs                            0.0
receiving_epa                               0.292378
receiving_2pt_conversions                          0
racr                                             0.0
target_share                                0.052632
air_yards_share                                  NaN
wopr                                             NaN
special_teams_tds                                0.0
fantasy_points                                  12.7
fantasy_points_ppr                              13.7
Name: 0, dtype: object

In [5]:
df.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [7]:
df.isnull().sum()

player_id                           0
player_name                     67401
player_display_name                 3
position                           72
position_group                     72
headshot_url                    59054
recent_team                         0
season                              0
week                                0
season_type                         0
opponent_team                       0
completions                         0
attempts                            0
passing_yards                       0
passing_tds                         0
interceptions                       0
sacks                               0
sack_yards                          0
sack_fumbles                        0
sack_fumbles_lost                   0
passing_air_yards                   0
passing_yards_after_catch           0
passing_first_downs                 0
passing_epa                    117297
passing_2pt_conversions             0
pacr                           117748
dakota                         119404
carries                             0
rushing_yards                       0
rushing_tds                         0
rushing_fumbles                     0
rushing_fumbles_lost                0
rushing_first_downs                 0
rushing_epa                     78790
rushing_2pt_conversions             0
receptions                          0
targets                             0
receiving_yards                     0
receiving_tds                       0
receiving_fumbles                   0
receiving_fumbles_lost              0
receiving_air_yards                 0
receiving_yards_after_catch         0
receiving_first_downs               0
receiving_epa                   27467
receiving_2pt_conversions           0
racr                            30279
target_share                    27467
air_yards_share                 54094
wopr                            54094
special_teams_tds                   0
fantasy_points                      0
fantasy_points_ppr                  0
dtype: int64

In [12]:
df[df['position'].isnull()]

,player_id,player_name,player_display_name,position,position_group,headshot_url,recent_team,season,week,season_type,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
1558,00-0005532,None,None,None,None,None,NO,1999,15,REG,...,0.0,-0.181085,0,NaN,0.021739,NaN,NaN,0.0,0.0,0.0
1559,00-0005532,None,None,None,None,None,NO,1999,16,REG,...,0.0,0.207961,0,0.000,0.037037,NaN,NaN,0.0,0.5,1.5
1560,00-0005532,None,None,None,None,None,NO,1999,17,REG,...,1.0,0.359601,0,0.000,0.042553,NaN,NaN,0.0,0.8,1.8
3990,00-0027567,None,Steve Maneri,None,None,None,KC,2011,12,REG,...,0.0,-0.529329,0,0.000,0.035714,-0.004902,0.050140,0.0,0.1,1.1
3991,00-0027567,None,Steve Maneri,None,None,None,KC,2011,16,REG,...,0.0,-0.537799,0,0.000,0.027778,0.029091,0.062030,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3703,00-0029675,None,Trent Richardson,None,None,None,IND,2014,13,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,1.2,1.2
3704,00-0029675,None,Trent Richardson,None,None,None,IND,2014,14,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,3.0,3.0
3705,00-0029675,None,Trent Richardson,None,None,None,IND,2014,15,REG,...,1.0,-1.372445,0,1.125,0.088235,0.022099,0.147823,0.0,4.1,6.1
3706,00-0029675,None,Trent Richardson,None,None,None,IND,2014,16,REG,...,0.0,-1.681711,0,1.600,0.045455,0.018797,0.081340,0.0,0.9,2.9
3707,00-0029675,None,Trent Richardson,None,None,None,IND,2014,17,REG,...,0.0,0.842205,0,9.000,0.028571,0.003690,0.045440,0.0,2.0,3.0

In [16]:
# Remove nulls
df = df[~(df['player_display_name'].isnull()) & ~(df['position'].isnull())]
df.isnull().sum()

player_id                           0
player_name                     67329
player_display_name                 0
position                            0
position_group                      0
headshot_url                    58982
recent_team                         0
season                              0
week                                0
season_type                         0
opponent_team                       0
completions                         0
attempts                            0
passing_yards                       0
passing_tds                         0
interceptions                       0
sacks                               0
sack_yards                          0
sack_fumbles                        0
sack_fumbles_lost                   0
passing_air_yards                   0
passing_yards_after_catch           0
passing_first_downs                 0
passing_epa                    117225
passing_2pt_conversions             0
pacr                           117676
dakota                         119332
carries                             0
rushing_yards                       0
rushing_tds                         0
rushing_fumbles                     0
rushing_fumbles_lost                0
rushing_first_downs                 0
rushing_epa                     78767
rushing_2pt_conversions             0
receptions                          0
targets                             0
receiving_yards                     0
receiving_tds                       0
receiving_fumbles                   0
receiving_fumbles_lost              0
receiving_air_yards                 0
receiving_yards_after_catch         0
receiving_first_downs               0
receiving_epa                   27459
receiving_2pt_conversions           0
racr                            30270
target_share                    27459
air_yards_share                 54083
wopr                            54083
special_teams_tds                   0
fantasy_points                      0
fantasy_points_ppr                  0
dtype: int64

In [18]:
columns = ['completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 
       'passing_2pt_conversions', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs',
       'receiving_2pt_conversions', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr']

seasonal_agg_df = df.groupby(
    ['player_id', 'player_display_name', 'position', 'position_group', 'season', 'season_type'], as_index=False)[columns].sum()

In [19]:
seasonal_agg_df

,player_id,player_display_name,position,position_group,season,season_type,completions,attempts,passing_yards,passing_tds,...,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_2pt_conversions,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0000003,Abdul-Karim al-Jabbar,RB,RB,1999,REG,0,0,0.0,0,...,1,0.0,0.0,0.0,0.0,5.0,0,0.0,64.699997,81.699997
1,00-0000003,Abdul-Karim al-Jabbar,RB,RB,2000,REG,0,0,0.0,0,...,0,0.0,0.0,0.0,0.0,0.0,0,0.0,-0.200000,-0.200000
2,00-0000007,Rabih Abdullah,RB,RB,1999,REG,0,0,0.0,0,...,0,0.0,0.0,0.0,0.0,0.0,0,0.0,2.300000,4.300000
3,00-0000007,Rabih Abdullah,RB,RB,2000,REG,0,0,0.0,0,...,0,0.0,0.0,0.0,0.0,1.0,0,0.0,8.400000,10.400000
4,00-0000007,Rabih Abdullah,RB,RB,2001,REG,0,0,0.0,0,...,0,0.0,0.0,0.0,0.0,2.0,0,0.0,6.600000,8.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18446,00-0039917,Michael Penix,QB,QB,2024,REG,61,105,775.0,3,...,0,0.0,0.0,0.0,0.0,0.0,0,0.0,44.099998,44.099998
18447,00-0039918,Caleb Williams,QB,QB,2024,REG,351,562,3541.0,20,...,0,0.0,0.0,0.0,0.0,0.0,0,0.0,254.539993,254.539993
18448,00-0039919,Rome Odunze,WR,WR,2024,REG,0,0,0.0,0,...,3,2.0,1.0,1398.0,253.0,37.0,0,0.0,90.900002,144.899994
18449,00-0039920,Malachi Corley,WR,WR,2024,REG,0,0,0.0,0,...,0,0.0,0.0,50.0,5.0,1.0,0,0.0,4.200000,7.200000
18450,00-0039921,Trey Benson,RB,RB,2024,REG,0,0,0.0,0,...,0,0.0,0.0,-19.0,78.0,3.0,0,0.0,41.000000,47.000000